[package]
name = "learn-web-with-rust"
version = "0.1.0"
authors = ["metmirr <metin7087@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "1.0.5"
listenfd = "0.3.3"
